package com.tencent.dal.dataobject;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.classify
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String classify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.timestamp
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private Date timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.path
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.value0
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String value0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.value1
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String value1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.value2
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String value2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.classify
     *
     * @return the value of article.classify
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.classify
     *
     * @param classify the value for article.classify
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setClassify(String classify) {
        this.classify = classify == null ? null : classify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.timestamp
     *
     * @return the value of article.timestamp
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.timestamp
     *
     * @param timestamp the value for article.timestamp
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.path
     *
     * @return the value of article.path
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.path
     *
     * @param path the value for article.path
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.value0
     *
     * @return the value of article.value0
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getValue0() {
        return value0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.value0
     *
     * @param value0 the value for article.value0
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setValue0(String value0) {
        this.value0 = value0 == null ? null : value0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.value1
     *
     * @return the value of article.value1
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getValue1() {
        return value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.value1
     *
     * @param value1 the value for article.value1
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setValue1(String value1) {
        this.value1 = value1 == null ? null : value1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.value2
     *
     * @return the value of article.value2
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getValue2() {
        return value2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.value2
     *
     * @param value2 the value for article.value2
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setValue2(String value2) {
        this.value2 = value2 == null ? null : value2.trim();
    }
}