package com.tencent.dal.dataobject;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.nickname
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.email
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.article_id
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.timestamp
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private Date timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.value0
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String value0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.value1
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String value1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.value2
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    private String value2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.nickname
     *
     * @return the value of comment.nickname
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.nickname
     *
     * @param nickname the value for comment.nickname
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.email
     *
     * @return the value of comment.email
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.email
     *
     * @param email the value for comment.email
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment
     *
     * @return the value of comment.comment
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment
     *
     * @param comment the value for comment.comment
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.article_id
     *
     * @return the value of comment.article_id
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.article_id
     *
     * @param articleId the value for comment.article_id
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.timestamp
     *
     * @return the value of comment.timestamp
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.timestamp
     *
     * @param timestamp the value for comment.timestamp
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.value0
     *
     * @return the value of comment.value0
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getValue0() {
        return value0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.value0
     *
     * @param value0 the value for comment.value0
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setValue0(String value0) {
        this.value0 = value0 == null ? null : value0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.value1
     *
     * @return the value of comment.value1
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getValue1() {
        return value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.value1
     *
     * @param value1 the value for comment.value1
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setValue1(String value1) {
        this.value1 = value1 == null ? null : value1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.value2
     *
     * @return the value of comment.value2
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public String getValue2() {
        return value2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.value2
     *
     * @param value2 the value for comment.value2
     *
     * @mbggenerated Fri Feb 13 20:40:41 CST 2015
     */
    public void setValue2(String value2) {
        this.value2 = value2 == null ? null : value2.trim();
    }
}